// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: sync_service.proto

package searchGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *InputUserRequest) Reset() {
	*x = InputUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputUserRequest) ProtoMessage() {}

func (x *InputUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputUserRequest.ProtoReflect.Descriptor instead.
func (*InputUserRequest) Descriptor() ([]byte, []int) {
	return file_sync_service_proto_rawDescGZIP(), []int{0}
}

func (x *InputUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type InputUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InputUserResponse) Reset() {
	*x = InputUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputUserResponse) ProtoMessage() {}

func (x *InputUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputUserResponse.ProtoReflect.Descriptor instead.
func (*InputUserResponse) Descriptor() ([]byte, []int) {
	return file_sync_service_proto_rawDescGZIP(), []int{1}
}

type InputArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Article *Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
}

func (x *InputArticleRequest) Reset() {
	*x = InputArticleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputArticleRequest) ProtoMessage() {}

func (x *InputArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputArticleRequest.ProtoReflect.Descriptor instead.
func (*InputArticleRequest) Descriptor() ([]byte, []int) {
	return file_sync_service_proto_rawDescGZIP(), []int{2}
}

func (x *InputArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type InputArticleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InputArticleResponse) Reset() {
	*x = InputArticleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputArticleResponse) ProtoMessage() {}

func (x *InputArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputArticleResponse.ProtoReflect.Descriptor instead.
func (*InputArticleResponse) Descriptor() ([]byte, []int) {
	return file_sync_service_proto_rawDescGZIP(), []int{3}
}

var File_sync_service_proto protoreflect.FileDescriptor

var file_sync_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x72, 0x70, 0x63,
	0x1a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x38, 0x0a, 0x10, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44,
	0x0a, 0x13, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47,
	0x72, 0x70, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xaa, 0x01, 0x0a,
	0x0b, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x09,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x47, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47,
	0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x47, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_service_proto_rawDescOnce sync.Once
	file_sync_service_proto_rawDescData = file_sync_service_proto_rawDesc
)

func file_sync_service_proto_rawDescGZIP() []byte {
	file_sync_service_proto_rawDescOnce.Do(func() {
		file_sync_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_service_proto_rawDescData)
	})
	return file_sync_service_proto_rawDescData
}

var file_sync_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sync_service_proto_goTypes = []interface{}{
	(*InputUserRequest)(nil),     // 0: searchGrpc.InputUserRequest
	(*InputUserResponse)(nil),    // 1: searchGrpc.InputUserResponse
	(*InputArticleRequest)(nil),  // 2: searchGrpc.InputArticleRequest
	(*InputArticleResponse)(nil), // 3: searchGrpc.InputArticleResponse
	(*User)(nil),          // 4: searchGrpc.User
	(*Article)(nil),       // 5: searchGrpc.Article
}
var file_sync_service_proto_depIdxs = []int32{
	4, // 0: searchGrpc.InputUserRequest.user:type_name -> searchGrpc.User
	5, // 1: searchGrpc.InputArticleRequest.article:type_name -> searchGrpc.Article
	0, // 2: searchGrpc.SyncService.InputUser:input_type -> searchGrpc.InputUserRequest
	2, // 3: searchGrpc.SyncService.InputArticle:input_type -> searchGrpc.InputArticleRequest
	1, // 4: searchGrpc.SyncService.InputUser:output_type -> searchGrpc.InputUserResponse
	3, // 5: searchGrpc.SyncService.InputArticle:output_type -> searchGrpc.InputArticleResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_service_proto_init() }
func file_sync_service_proto_init() {
	if File_sync_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sync_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputArticleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputArticleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_service_proto_goTypes,
		DependencyIndexes: file_sync_service_proto_depIdxs,
		MessageInfos:      file_sync_service_proto_msgTypes,
	}.Build()
	File_sync_service_proto = out.File
	file_sync_service_proto_rawDesc = nil
	file_sync_service_proto_goTypes = nil
	file_sync_service_proto_depIdxs = nil
}
